const puppeteer = require('puppeteer');
const createCsvWriter = require('csv-writer').createObjectCsvWriter;
let data = [];
let positions = [
  'Oyo Software Developer',
  'Oyo Software Engineer',
  'Oyo Product Manager'
];
let positionzero = [
  'Adyen Java Developer',
  'Deliveroo Data Scientist',
  'Samsara Product Manager',
  'Stripe Data Scientist',
  'Accenture Creative Lead',
  'Adobe UX Designer',
  'Adobe Engineering Manager',
  'Agoda Senior Software Engineer',
  'Agoda Full Stack Engineer',
  'Agoda Data Analyst',
  'Google Program Manager',
  'Uber Software Developer',
  'Tech Mahindra Senior Software Engineer',
  'Tech Mahindra Software Engineer',
  'Tinder Android Developer',
  'Tinder Product Manager',
  'Tinder Data Scientist',
  'Tinder Machine Learning Scientist',
  'Tinder Product Designer',
  'Transferwise Software Engineer',
  'Transferwise Product Designer',
  'Twitter Site Reliability Engineer',
  'Twitter Program Manager',
  'Twitter Product Designer',
  'Twitter UX Researcher',
  'Uber Product Marketing Manager',
  'VeriSign Software Engineer',
  'VeriSign Program Manager',
  'VMware Software Consultant',
  'Walt Disney Data Analyst'
];
let positionnext = [
  'Tech Mahindra Associate Software Engineer',

  'Tinder Software Engineer',

  'Twitter Senior Software Engineer',

  'Uber Senior Software Engineer',
  'Uber Data Scientist',

  'Walt Disney Graphic Designer',
  'Walt Disney Visual Designer',
  'Walt Disney UX Designer',
  'Wealthfront Software Engineer',
  'Wealthfront Product Manager',
  'Wealthfront Data Scientist',
  'Whatsapp Software Engineer',
  'Whatsapp Product Designer',
  'Workday Associate Applications Developer',
  'Workday Associate Software Engineer',
  'YouTube Software Engineer New Grad',
  'YouTube Product Specialist',
  'YouTube UX Researcher',
  'YouTube UX Designer',
  'Zalando Junior Data Analyst',
  'Zalando UX Designer',
  'Zalando Product Designer',
  'Amazon Software Development Engineer',
  'Intel Network Validation Engneer',
  'Square Senior Product Manager',
  'Agoda Software Developer',
  'Airbnb Principal Software Engineer',
  'Akamai Data Scientist',
  'Amazon Tax Senior Program Manager',
  'Amazon Program Manager',
  'Amazon UX Designer',
  'Amazon Senior Product Manager',
  'Amazon Machine Learning Engineer',
  'Amazon Senior Program Manager',
  'Amazon Web Services Systems Development Engineer',
  'Apple Customer Service',
  'Apple Product Manager',
  'Apple UX Designer',
  'Apple Specialist',
  'Arista Networks Software Engineer',
  'Atlassian Support Engineer',
  'Autodesk Software Engineer',
  'Booking.com Product Marketing Manager',
  'Booking.com Android Developer',
  'Booking.com Data Specialist',
  'Booking.com  UX Researcher',
  'Booking.com Data Analyst',
  'Walt Disney Software Developer',
  'Ebay Software Engineer',
  'Facebook Front End Dev. (UI engineer)',
  'Facebook Analyst',
  'Facebook UX Designer',
  'Facebook Machine Learning Engineer',
  'Facebook Production Engineer',
  'Facebook Program Manager',
  'Google Admin Business Partner',
  'Google Software Developer',
  'Huawei Network Engineer',
  'Huawei R&D AI Data Security Engineer',
  'IBM Software Developer',
  'Intel Software Developer',
  'Intuit Data Analyst',
  'J.P. Morgan Analyst',
  'Lyft Assistant Product Manager',
  'Lyft Software Engineer',
  'Lyft Data Analyst',
  'Mastercard Software Developer',
  'Mastercard Java Developer',
  'Microsoft Support Engineer',
  'Microsoft UX Designer',
  'Netflix Software Engineer',
  'NVIDIA ASIC Design Engineer',
  'Oracle Developer',
  'Palantir Forward Deployed Engineer',
  'Palo Alto Networks Software Quality Assurance Engineer',
  'Qualcomm Software Engineer',
  'Qualcomm Embedded Software Engineer',
  'Red Hat Software Engineer',
  'Red Hat Data Analyst',
  'Robinhood Customer Service Manager',
  'Samsara Software Engineer',
  'Splunk Software Engineer',
  'Spotify Data Scientist',
  'Spotify Senior Data Engineer',
  'Square Software Engineer',
  'Stripe Software Engineering Manager',
  'Twitter Data Scientist',
  'VMware Technical Support Engineer',
  'Workday Software Applications Engineer',
  'Zalando Software Engineer',
  'Zalando Java Developer',
  'Zalando Senior Software Engineer',
  'Zalando Data Science',
  'Zalando Data Analyst',
  'Zalando Full Stack Developer',
  'Zalando Network Engineer',
  'Accenture Technical Analyst',
  'Accenture Web Developer',
  'Accenture Senior Software Engineer',
  'Accenture Data Analyst',
  'Accenture UX Designer',
  'Accenture Senior Java Software Developer',
  'Accenture Software Tester',
  'Adobe Senior Product Manager',
  'Adobe Senior Financial Analyst',
  'Adobe Quality Engineer',
  'Adobe Quality Assurance Engineer',
  'Adobe UI Softwrae Engineer',
  'Advanced Micro Devices Software Engineer',
  'Advanced Micro Devices Product Development Engineer',
  'Applied Materials Java Developer',
  'Adyen Implementation Engineer',
  'Agoda Senior Application Engineer',
  'Agoda Senior Data Analyst',
  'Agoda Senior Product Owmer',
  'Agoda Content Manager',
  'Agoda Partnership Coordinator',
  'Agoda Product Manager',
  'Agoda Test Manager',
  'Agro Al Software Engineer',
  'AirbBnB Full Stack Developer',
  'AirBnB Product Manager',
  'AirbnB Data Analyst',
  'AirbnB Territory Manager',
  'Akamai Data Architect',
  'Akamai Business Operations Analyst',
  'Akamai Senior Program Manager',
  'Akamai Systems Administrator',
  'Akamai Network Engineer',
  'Akamai Technical Support Lead',
  'Amazon Software Development Engineer in Test',
  'Amazon IT Support Engineer',
  'Amazon Supply chain program manager',
  'Amazon Quality Assurance Engineer',
  'Amazon iOS Developer',
  'Amazon Engagement Manager',
  'Amazon Engneering Leader',
  'Amazon Principal Technical Program Manager',
  'Amazon Senior Development Manager',
  'Amazon UX Manager',
  'Amazon Technical Support Engineer',
  'Amazon Front End Engineer',
  'Amazon Senior Technical Program Manager',
  'Amazon Support Engineer',
  ' Amazon Web Services Custromer Support Associate',
  'Amdocs Software Developer',
  'Ameriprise Software Engineer',
  'Analog Devices Analog Design Engineer',
  'Apple Software Engineer',
  'Apple Software Developer ',
  'Apple At Home Advisor',
  'Apple IT Support Engineer',
  'Apple Engineering Program Manager',
  'Apple Data Analyst',
  'Apple iOS Developer',
  'Apple Retail Manager',
  'Apple Product Owner',
  'Apple Data Engineer',
  'Apple Automation Test Engineer',
  'Apple Business Intellegence Analyst',
  'Argo AI Engineering Manager',
  'Argo AI Software Engineering Manager',
  'Aricent Analog layout Engineer',
  'Atlassian Senior Product Designer',
  'Atlassian Site Reliability Engineer',
  'Barclays Software Developer',
  'Betterment Software Engineer',
  'Booking.com Senior Product Manager',
  'Booking.com iOS Developer',
  'Booking.com Project Manager- Finance',
  'Booking.com Marketing Specialist',
  'Booking.com Software Engineer',
  'Booking.com UX Designer',
  'Booking.com User Researcher',
  'Booking.com CRM Systems and Tooling Development Specialist',
  'Booking.com Full Stack Developer',
  'Capgemini Software Developer',
  'Capgemini Senior Software Engineer',
  'Capgemini UX Designer',
  'Capgemini Business Analyst',
  'Capital One Data Scientist',
  'Capital One Principal Software Engineer',
  'Cisco Network Consulting Engineer',
  'Cisco Systems Engineer',
  'Cisco Data Scientist',
  'Cisco Data Analyst',
  'Cisco UI Lead',
  'Cisco QA Engineer',
  'Cisco C++ Developer',
  'Cisco Assoociate Consulting Engineer',
  'Cisco Technical Consultant',
  'Cisco Test Lead',
  'Cisco Consulting Engineer',
  'Cisco Techical Consulting Engineer (Routing & Switching)',
  'Cisco Software Developer',
  'Citrix Software Engineer',
  'Citrix Senior Software Engineer',
  'Citrix Lead Software Developer',
  'Cognizant UX Designer',
  'Cognizant UI Designer',
  'Cognizant Big Data Engineer',
  'Cognizant Senior Java Developer',
  'Cognizant Java Architect',
  'Coinbase Data Scientist',
  'Coinbase Software Engineer',
  'Coinbase Back End Developer',
  'Coinbase Senior Product Manager',
  'Coinbase iOS Engineer',
  'Comcast Customer Experience Representative',
  'Comcast Cyber Security Engineer',
  'Comcast Network Operations Engineer',
  'Databricks Software Developer',
  'Databricks Software Engineer',
  'Databricks Solution Architect',
  'Deliveroo Product Manager',
  'Deliveroo Software Engineer',
  'Deliveroo Data Analyst',
  'Deliveroo Java Developer',
  'Deliveroo Data Engineer',
  'Deliveroo Senior Software Engineer',
  'DeliveryHero Senior Product Manager',
  'DeliveryHero Data Scientist',
  'DeliveryHero Project Manager',
  'Dell Technologies Data Scientist',
  'Dell Technologies Senior Advisor Product Manager',
  'Dell Technologies Validation Engineer',
  'Deutsche Bank Software Developer',
  'Walt Disney Android Developer',
  'Walt Disney DevOps',
  'Dropbox Data Scientist',
  'Dropbox Product Designer',
  'Ebay Junior Software Engineer',
  'Ebay Senior Data Analyst',
  'Ebay Marketing Manager',
  'Ebay Analyst',
  'Facebook E5 Software Engineer',
  'Facebook Senior Product Manager',
  'Facebook Market Specialist',
  'Facebook Community Manager',
  'Facebook Public Policy Manager',
  'Facebook Technical Program Manager',
  'Facebook Systems Development Engineer',
  'Facebook Business Systems Analyst',
  'Facebook DevOps',
  'Facebook Decision Scientist',
  'Facebook Front End Engineer',
  'Facebook Solutions Engineer',
  'Facebook Python Engineer',
  'Facebook Content Manager',
  'Facebook Enforcement and Protection Manager',
  'Facebook Project Manager',
  'Facebook Customer Support Manager',
  'Facebook Engineering Leader',
  'Facebook Technical Product Manager',
  'Facebook Product Owner',
  'Facebook Partner Development Manager',
  'Facebook Principal Solution Architect',
  'Flexport Product Manager',
  'Flipkart Product Manager',
  'Flipkart Associate Product Manager',
  'FlixMobility Senior Software Engineer',
  'Fractal Analytics Data Scientist',
  'Fractal Analytics Machine Learning Engineer',
  'Fractal Analytics Python Engineer',
  'Full story Software Engineer',
  'Genpact Data Scientist',
  'Genpact Python Engineer',
  'Genpact Machine Learning Engineer',
  'GeoPhy Software Developer',
  'Goldman Sachs Business Analyst',
  'Goldman Sachs DevOps',
  'Goldman Sachs Quality Assurance Engineer',
  'Google Assistant Product Manager',
  'Google Business Operations Program Manager',
  'Google DevOps',
  'Google Senior Software Engineer',
  'Google Test Engineer',
  'Google UX Designer',
  'Google Principal Designer',
  'Google Sales Operations Manager',
  'Google Senior Product Manager',
  'Google Technical Specialist',
  'Google Quality Assurance Engineer',
  'Google iOS Developer',
  'Google Python Engineer',
  'Google Operations Analyst',
  'Google Machine Learning Engineer',
  'Google Material Technician',
  'Google Engineering Leader',
  'Google Engineering Manager',
  'Google Visual Designer',
  'Google Labeling Expert',
  'Google Business Systems Analyst(devices & software)',
  'Google Investigative Analyst',
  'Grab Product Manager',
  'Grab Product Designer',
  'Honeywell Developer',
  'Huawei WDM Engineer',
  'Huawei NTD-Wireless Engineer',
  'Huawei Data Communication Engineer',
  'Hudson River Trading Software Developer',
  'IBM Software Engineer',
  'IBM Associate Technical Engineer',
  'IBM Cloud Engineer',
  'IBM Data Scientist',
  'IBM Visual Designer',
  'IBM Content Designer',
  'IBM Front End Developer',
  'IBM Consultant',
  'IBM System Developer',
  'IBM Front End Developer',
  'ICIX Software Developer',
  'Infineon Technologies Process Engineer',
  'Infosys UX Designer',
  'Infosys Software Developer',
  'Intel SOC Pre-Si Verification Engineer',
  'Intel Process Engineer',
  'Intel Validation Engineer',
  'Intel Postdoctoral Researcher',
  'Intuit Senior Product Manager',
  'Intuit Sr. Data Analyst',
  'J.P. Morgan Business Analyst',
  'J.P. Morgan Change Control Manager',
  'J.P. Morgan Software Engineer',
  'Juniper Product Manager',
  'Leidos iOS Developer',
  'Lyft Software Developer',
  'Lyft Data Scientist',
  'Lyft Data Engineer',
  'Lyft Operations Analyst',
  'Mastercard Analytics Manager',
  'Mastercard Accounts Manager',
  'Mastercard Senior Software Engineer',
  'Mastercard Data Analyst',
  'Mastercard Technical Program Manager',
  'MessageBird Senior Software Engineer',
  'Micron Technologies Senior Analog Layout Engineer',
  'Micron Technology Process Engineer',
  'Micron Technology Process Integration',
  'Microsoft Senior Product Manager',
  'Microsoft Software Development Engineer in test',
  'Microsoft Hardware Engineering',
  'Microsoft Account Delivery Executive',
  'Microsoft DevOps',
  'Microsoft Azure Cloud Engineer',
  'Microsoft Senior Software Developer',
  'Microsoft Software Developer',
  'Microsoft Azure Support Engineer',
  'Microsoft Support Escalation Engineer',
  'Microsoft Product Design Engineer',
  'Microsoft Product Marketing Manager',
  'Mindgrub iOS Developer',
  'Motorola Solutions Software Engineer',
  'Motorola Solutions NOC  Analyst',
  'National Instruments Software Development',
  'National Instruments Engineer Leadership Program',
  'Netflix Machine Learning Engineer',
  'Netflix Enginering Leader',
  'Nokia UX Designer',
  'Noodle.ai Senior Database Engineer',
  'Noodle.ai Data Scientist',
  'NVIDIA Software Engineer',
  'NVIDIA System Software Engineer',
  'Oracle Data Scientist',
  'Oracle Senior Product Manager',
  'Oracle Python Engineer',
  'Oracle Machine Learning Engineer',
  'Oracle Software Development Manager',
  'Oracle Technical Program Manager',
  'Palantir Software Developer',
  'Palantir Accounts Receivables Analyst',
  'Palantir Product Designer',
  'Palantir Software Engineer',
  'Palo Alto Networks Product Manager',
  'Palo Alto Networks Systems Engineer',
  'Palo Alto Networks Data Engineer',
  'Panasonic Manufacturing Data Analyst',
  'Panasonic Energy Data Analyst',
  'Panasonic Energy Manufacturing Data Analyst',
  'PayPal Data Engineer',
  'PayPal Data Scientist',
  'PayPal Data Analyst',
  'PayPal Business Analyst',
  'Qualcomm Electrical Power Engineer',
  'Qualcomm RF System Engineer',
  'Qualcomm Validation Engineer',
  'Quora Software Engineer',
  'Quora Machine Learning Engineer',
  'Quora Analyst',
  'Red Hat Technical Support Engineer',
  'Red Hat Business Data Scientist',
  'Red Hat Data Information Analyst',
  'Reddit Senior Product Designer',
  'Ripple Front End Dev. (UI engineer)',
  'Ripple Software Engineer',
  'Robinhood Data Scientist',
  'Robinhood Backend Developer',
  'Robinhood iOS Engineer',
  'Salesforce Software Development Engineer in test',
  'Salesforce Senior Demo Engineer',
  'Salesforce Pre sales',
  'Salesforce Project Manager',
  'Salesforce UX Designer',
  'Salesforce Strategic Solutions Engineer',
  'Salesforce Lead Software engineer',
  'Salesforce Senior Developer',
  'Salesforce UI Designer',
  'Salesforce Full Stack Engineer',
  'Samsara Support Engineer',
  'Samsara Director Product Management',
  'Samsara Data Scientist',
  'Samsara Software Development Engineer',
  'Samsung Software Engineer',
  'Samsung Research Engineer',
  'Samsung SDS Business Intellegence Specialist',
  'Sandisk Analog Design Engineer',
  'SAP Software Engineer',
  'SAP Support Engineer',
  'SAP Product Manager',
  'SAP Data Scientist',
  'SAP Manufacturing Engineer',
  'SAP Java Developer',
  'SAP Hybris Developer',
  'Sarush Software Engineer',
  'Seagate Process Engineer',
  'Seagate Technology Test Engineer',
  'ServiceNow Software Development Engineer in test',
  'ServiceNow Technical Support Engineer',
  'ServiceNow Applications Developer',
  'Snap Inc. Event Manager',
  'Snap Inc. QA Engineer',
  'Snap Inc. Data Scientist',
  'Snap Inc. Network Automation Engineer',
  'Sony Engineer',
  'Sony Playstation Software Development Engineer in test',
  'Sony Playstation QA Engineer',
  'Soundcloud Data Scientist',
  'Splunk Software Engineer UI',
  'Splunk Senior Software engineer - Front End',
  'Splunk QA Manager',
  'Splunk Data Quality Analyst',
  'Splunk Tech Support Engineer',
  'Splunk Front End Engineer',
  'Spotify Front End Developer',
  'Spotify Back end developer',
  'Spotify Android Developer',
  'Spotify Senior Java Developer',
  'Spotify Senior product Manager',
  'Spotify Premium Conversion Campaign Manager',
  'Spotify Software Engineer',
  'Spotify Data Engineer',
  'Spotify Product Insights Manager',
  'Spotify Product Designer',
  'Spotify UX Designer',
  'Spotify Marketing Manager',
  'Spotify Andriod Engineer',
  'Spotify Product Marketing Manager',
  'Spotify Software Developer',
  'Square Software Engineer - Platform',
  'Square Technical Program Manager',
  'STMicroelectronics Analog Design Engineer',
  'STMicroelectronics Senior Software Developer',
  'Stripe Server Message Block Operations Specialist',
  'Stripe Sales Manager',
  'Stripe Senior Product Manager',
  'Stripe Account Manager',
  'Stripe Engineering Manager',
  'Tech Mahindra System Analyst',
  'Tech Mahindra QA Analyst',
  'Tech Mahindra Data Engineer',
  'Teleperformance Customer Care Representative (Hebrew)',
  'Texas Instruments Analog Design Engineer',
  'Transferwise Software Developer',
  'Transferwise Product Manager',
  'Transferwise Data Analyst',
  'Transferwise Product Marketing Manager',
  'Transferwise Product Development Manager',
  'Trend Micro Production Engineer',
  'Twitter Senior product Manager',
  'Twitter Product Manager',
  'Twitter Product Marketing Manager',
  'Twitter IT Systems Engineer',
  'Twitter Senior Business Analyst',
  'Twitter Software Developer',
  'Twitter UX Research Engineer',
  'Uber Android Developer',
  'Uber Product Manager',
  'Uber Software Engineer',
  'Uber Engineering Manager',
  'Uber Data Analyst',
  'Uber Product Designer',
  'Uber Program Manager',
  'Uber Product Analyst',
  'VMware Senior Android Developer',
  'VMware Senior Software Engineer',
  'VMware Senior Java Developer',
  'Vmware Windows System Administrator',
  'VMware Software Developer',
  'Walt Disney Software Engineer',
  'Walt Disney Senior Software Engineer',
  'Wipro Software Developer',
  'Wipro Junior Software Developer',
  'Workday Product Manager',
  'Workday Senior Software Engineer',
  'Workday Performance Engineer',
  'Workday QA Engineer',
  'Workday Financials Implementation Consultant',
  'Workday iOS Developer',
  'Workday Senior BI analyst',
  'Workday Principal Software Engineer',
  'Workday Mobile Developer',
  'Xilinx Analog Design Engineer',
  'Xilinx Software Developer',
  'YouTube Software Engineer',
  'YouTube Data Analyst',
  'YouTube Policy Enforcement Specialist',
  'Zalando Senior Android Engineer',
  'Zalando Senior Data Analyst',
  'Zalando Senior Product Specialist',
  'Zalando Front End Developer',
  'Zalando Junior Backend Engineer',
  'Zalando iOS Developer',
  'Zalando Backend Engineer (Java)',
  'Zalando Research Engineer',
  'PwC Data Scientist',
  'PwC Machine Learning Engineer',
  'Trivago Data Analyst',
  'HCL UX Designer',
  'HCL Data Engineering',
  'HCL Software Engineer',
  'Credit Suisse Software Developer',
  'Credit Karma Innovations Manager',
  'Coupang Data Scientist',
  'Bird Data Analyst',
  'Peloton Technical Program Manager',
  'Medlane Data Scientist',
  'Bonify Data Scientist',
  'Go-running.com Data Scientist',
  'Espirit Data Scientist',
  'Frontinet Sytems Engineer',
  'Talroo Site Reliability Engineer',
  'NBUniversal Data Scientist',
  'Target Product Owner',
  'Yelp Software Engineer',
  'Motiva Cloud Security Architect',
  'Western Digital Technical Support Engineer',
  'ChannelSight Data Analyst',
  'Zendesk Product Analyst',
  'ONQ Financials Software Developer',
  'Oyo UX Designer',
  'Sprinkler UX Designer',
  'Nutanix UX Designer',
  'Nomis Solutions Data Scientist',
  'DoorDash Support strategy and Operations Manager',
  'Confluent.io Technical Program Manager',
  'Canopy Growth Product Specialist',
  'Novelis  Data Scientist',
  'LinkedIn Build And Release Engineer',
  'LinkedIn Site Reliability Engineer',
  'LinkedIn Software Engineer',
  'Curate Retail Group Product Manager',
  'United Health Group Software Developer',
  'Microchip Software Developer',
  'Cushman Wakefield Data Analyst',
  'McKesson Business Insights Analyst',
  'MS Exchange Support Engineer',
  'Hawai Technologies Software Developer',
  'Nextag Software and Services Full Stack Developer',
  'Capco Data Analyst',
  'Tchibo B2B EDI Senior Consultant',
  'Cyient Physical Design Engineer',
  'TSYS Front End Developer',
  'Concur Software Engineer',
  'Service Now Product Manager',
  'Voith  Data Scientist',
  'Atlassian design manager',
  'TikTok Product Manager',
  'Skype Product Manager',
  'New York Times Data Engineer',
  'Digicel Core Network Engineer',
  'Dynatrace Software Developer',
  'Revoult Product Marketing Manager',
  'Carta  Software Engineer',
  'NTT Senior Network Automation Engineer',
  'Totota Connected Cloud Infrastructure DevOps Engineer',
  'Appirio Python Data Analyst',
  'Ideo Product Designer',
  'Ideo Interaction Designer',
  'Walmart Labs Senior Product Designer',
  'TradeByte Senior Software Developer',
  'Tek Experts Software Support Engineer - Azure',
  'Accenture Business Analyst',
  'Accenture Associate Software Engineer',
  'Accenture Software Engineer',
  'Accenture Software Engineering Analyst',
  'Accenture Product Manager',
  'Acer Product Manager',
  'Adobe Senior Software Engineer',
  'Adobe Program Manager',
  'Adobe Data Scientist',
  'Adobe Research Scientist',
  'Advanced Micro Devices Senior Design Engineer',
  'Advanced Micro Devices Design Engineer',
  'Advanced Micro Devices Physical Design Engineer',
  'Advanced Micro Devices Research Scientist',
  'Advanced Micro Devices UI Developer',
  'Adyen Technical Support Engineer',
  'Adyen Data Scientist',
  'Adyen UX Designer',
  'Agoda Product Marketing Manager',
  'Agoda Data Scientist',
  'Agoda UX Designer',
  'AirBnB Software Engineer',
  'AirBnB Software Engineer New Grad',
  'AirBnB Front end Engineer',
  'AirBnB Senior Software Engineer',
  'AirBnB Software Engineer (Backend)',
  'AirBnB IOS Engineer',
  'AirBnB Product Designer',
  'AirBnB Experience Designer',
  'AirbnB Frontend Engineer',
  'AirbnB Android Engineer',
  'Akamai Software Engineer',
  'Akamai Senior Software Engineer',
  'Akamai Systems Software Engineer',
  'Akamai QA Engineer',
  'Akamai Senior QA Engineer',
  'Akamai Customer Solutions Engineer',
  'Akamai Applications Software Engineer',
  'Akamai Platform Operations Engineer',
  'Akamai Solutions Engineer',
  'Akamai Product Manager',
  'Akamai Program Manager',
  'Akamai Data Analyst',
  'Akamai UX Designer',
  'Akamai Visual Designer',
  'Alibaba Software Engineer',
  'Alibaba Algorithm Engineer',
  'Alibaba Senior Product Manager',
  'Alibaba Data Scientist',
  'Alibaba Data Analyst',
  'Alibaba Research Analyst',
  'Alibaba UX Designer',
  'Amazon Senior UX Designer',
  'Amazon Visual Designer',
  'Apple Hardware Engineer',
  'Apple Senior Software Engineer',
  'Apple Product Specialist',
  'Apple Senior Data Scientist',
  'Apple UI Designer',
  'Apple Visual Designer',
  'Apple Product Designer',
  'Apple Senior Product Designer',
  'Apple Computer sales specialist',
  'Argo AI Software Engineer',
  'Atlassian Software Engineer',
  'Atlassian Senior Software Engineer',
  'Atlassian Senior Support Engineer',
  'Atlassian Site Reliability Engineer',
  'Atlassian Product Manager',
  'Atlassian Data Scientist',
  'Atlassian Data Analyst',
  'Atlassian Senior UX Researcher',
  'Autodesk Senior Software Engineer',
  'Autodesk Graduate Software Engineer',
  'Autodesk Software QA Engineer',
  'Autodesk Product Manager',
  'Autodesk Product Support Specialist',
  'Autodesk Big Data Analyst',
  'Autodesk UX Designer',
  'Autodesk Senior UX Designer',
  'Betterment Product Manager',
  'Betterment Product Designer',
  'Bird Data Analyst',
  'Bird Senior Data Scientist',
  'Blockchain Inc UX Designer',
  'Booking.com Data Scientist',
  'Booking.com Machine Learning',
  'Broadcom Software Engineer',
  'Broadcom IC Design Engineer',
  'Bumble Product Marketing Coordinator',
  'Canon Software Engineer',
  'Canon Product Marketing Manager',
  'Canon Data Analyst',
  'Capgemini Software Engineer',
  'Capgemini Associate Software Engineer',
  'Capgemini Test Engineer',
  'Capgemini Data Analyst',
  'Cisco Senior Software Engineer',
  'Cisco Customer Support Engineer',
  'Cisco Associate Systems Engineer',
  'Cisco IT Engineer',
  'Cisco Hardware Engineer',
  'Cisco Software QA Engineer',
  'Cisco Program Manager',
  'Cisco Principal Product Designer',
  'Cisco UX Designer',
  'Cisco Senior UX Designer',
  'Cisco UI Developer',
  'Citrix Technical Support Engineer',
  'Citrix Software Test Engineer',
  'Citrix Staff Software Engineer',
  'Citrix Product Manager',
  'Citrix Senior Product Manager',
  'Citrix Product Marketing Manager',
  'Citrix Data Scientist - Network Security',
  'Citrix UX Designer',
  'Citrix Senior UI Developer',
  'Citrix Product Designer',
  'Citrix Senior Product Designer',
  'Cognizant Software Engineer',
  'Cognizant Senior Software Engineer',
  'Cognizant Associate Software Engineer',
  'Cognizant Data Scientist',
  'Coinbase Product Manager',
  'Coinbase Data Analyst',
  'Comcast Network Engineer',
  'Comcast Senior Software Engineer',
  'Comcast Product Manager',
  'Comcast Senior Product Manager',
  'Comcast Data Scientist',
  'Comcast Data Analyst',
  'Databricks Data Scientist',
  'Databricks UX Designer',
  'Deliveroo Engineering Manager',
  'Deliveroo Program Manager',
  'Deliveroo Senior Data Scientist',
  'Deliveroo Graphic Designer',
  'Deliveroo User Researcher',
  'DeliveryHero Product Manager',
  'DeliveryHero Senior Product Manager',
  'DeliveryHero Senior UX Designer',
  'Dell Technologies Software Engineer',
  'Dell Technologies Senior Software Engineer',
  'Dell Technologies Program Manager',
  'Dell Technologies Product Marketing Manager',
  'Dell Technologies Data Analyst',
  'Dell Technologies UX Designer',
  'Dell Technologies UX Architect',
  'Dell Technologies UI Developer',
  'Drive.ai Software Engineer',
  'Drive.ai Senior Product Manager',
  'Drive.ai Program Manager',
  'Dropbox Product Manager',
  'Dropbox Product Marketing Manager',
  'Dropbox User Operations Engineer',
  'Dropbox Senior Software Engineer',
  'Dropbox Technical Support Engineer',
  'Dropbox Program Manager',
  'Dropbox Machine Learning',
  'Dropbox UX Designer',
  'Dropbox Web Designer',
  'Dropbox Product Analyst',
  'Ebay Senior Software Engineer',
  'Ebay Product Manager',
  'Ebay Senior Product Manager',
  'Ebay Data Scientist',
  'Ebay Data Analyst',
  'Ebay Interaction Designer',
  'Ebay UI Designer',
  'Ebay UX Designer',
  'Evernote Software Engineer',
  'Evernote Product Manager',
  'Evernote Senior Product Manager',
  'Evernote Data Scientist',
  'Evernote Senior Data Analyst',
  'Evernote Product Designer',
  'Flexport Software Engineer',
  'Flexport Data Scientist',
  'Flexport Senior Product Designer',
  'Fujitsu Software Engineer',
  'Fujitsu Senior Software Engineer',
  'Fujitsu Systems Engineer',
  'Fujitsu Product Manager',
  'Fujitsu Data Analyst',
  'Gemalto Software Engineer',
  'Gemalto Senior Software Engineer',
  'Gemalto Embedded Software Engineer',
  'Gemalto Machine Learning',
  'Glint Senior Software Engineer',
  'Glint Data Scientist',
  'Goldman Sachs Operations Analyst',
  'Goldman Sachs Investment Banking Analyst',
  'Google Engineering Practicum',
  'Google Software Engineer in test',
  'Google Associate Product Manager',
  'Google Interaction Designer',
  'Google Product Designer',
  'Google Industrial Designer',
  'Google Community Manager',
  'Grab Software Engineer',
  'Grab Software Engineer (Backend)',
  'Grab Senior Software Engineer',
  'Grab Data Scientist',
  'Grab UX Designer',
  'Grab UI and Visual Developer',
  'HP Systems Software Engineer',
  'HP Software Engineer',
  'HP Senior Software Engineer',
  'HP Technical Support Engineer',
  'HP Program Manager',
  'HP Product Manager',
  'HP Data Scientist',
  'HP Lead UX Designer',
  'HP Industrial Designer',
  'HP UI Designer',
  'Huawei Software Engineer',
  'Huawei Senior Software Engineer',
  'Huawei Core Network Engineer',
  'Huawei Associate Software Engineer',
  'Huawei Technical Support Engineer',
  'Huawei Research Engineer',
  'Huawei Software Test Engineer',
  'Huawei Wireless Engineer',
  'Huawei RF Engineer',
  'Huawei Product Manager',
  'Huawei Data Scientist',
  'Huawei Senior Graphic Designer',
  'IBM Associate Systems Engineer',
  'IBM Senior Software Engineer',
  'IBM Systems Engineer',
  'IBM Associate Software Engineer',
  'IBM Senior Systems Engineer',
  'IBM Technical Support Engineer',
  'IBM Entry Level Software Engineer',
  'IBM Product Manager',
  'IBM Product Designer',
  'IBM UX Designer',
  'Infineon Technologies Software Engineer',
  'Infosys Systems Engineer',
  'Infosys Software Engineer',
  'Infosys Senior Systems Engineer',
  'Infosys Data Analyst',
  'Infosys Data Scientist',
  'Intel Software Engineer',
  'Intel Component Design Engineer',
  'Intel Hardware Engineer',
  'Intel Senior Process Engineer',
  'Intel Systems Validation Engineer',
  'Intel Systems Engineer',
  'Intel Product Manager',
  'Intel Data Scientist',
  'Intel Data Analyst',
  'Intel Research Scientist',
  'Intel Interaction Designer',
  'Intuit Senior Software Engineer',
  'Intuit Data Scientist',
  'Intuit Interaction Designer',
  'Intuit UX Designer',
  'J.P. Morgan Personal Banker',
  'J.P. Morgan Operations Analyst',
  'Leidos Software Engineer',
  'LG Software Engineer',
  'LG Research Engineer',
  'LG Senior Software Engineer',
  'LG Assistant Product Manager',
  'LG Data Scientist',
  'LG Senior Industrial Designer',
  'Lyft Senior Software Engineer',
  'Lyft Product Marketing Manager',
  'Lyft Product Designer',
  'Lyft Learning Experience Designer',
  'Mastercard Associate Software Engineer',
  'Mastercard Product Manager',
  'Mastercard UX Designer',
  'MessageBird Product Manager',
  'Micron Technology Product Engineer',
  'Micron Technology Engineer',
  'Microsoft Senior Software Development Engineer',
  'Microsoft UI Developer',
  'Mixpanel Software Engineer',
  'Mixpanel Product Designer',
  'Mixpanel Communications Designer',
  'Motorola Solutions Senior Software Engineer',
  'Motorola Solutions Systems Engineer',
  'Motorola Solutions Electrical Engineer',
  'Motorola Solutions Embedded Software Engineer',
  'Motorola Solutions Test Engineer',
  'Motorola Solutions Senior Product Manager',
  'Motorola Solutions Data Analyst',
  'Motorola Solutions UX Designer',
  'Motorola Solutions UI Developer',
  'Naspers Web Developer',
  'National Instruments Software Engineer',
  'National Instruments ELP Engineer',
  'National Instruments Applications Engineer',
  'National Instruments Hardware Engineer',
  'National Instruments Digital Hardware Engineer',
  'National Instruments Analog Hardware Engineer',
  'National Instruments Test Engineer',
  'National Instruments Product Manager',
  'National Instruments Junior User Experience Designer',
  'NetApp Software Engineer',
  'NetApp Technical Support Engineer',
  'NetApp Systems Engineer',
  'NetApp Senior Software Engineer',
  'NetApp Program Manager',
  'NetApp Product Manager',
  'NetApp Senior Program Manager',
  'NetApp Senior Product Manager',
  'NetApp Data Scientist',
  'NetApp Data Analyst',
  'NetApp Product Designer',
  'NetEase Software Engineer',
  'NetEase Product Manager',
  'Netflix Data Scientist',
  'Netflix Product Manager',
  'Nokia Software Engineer',
  'Nokia R&D Engineer',
  'Nokia Senior Software Engineer',
  'Nokia Product Manager',
  'Nokia Program Manager',
  'Nokia Data Scientist',
  'Nokia Big Data Analyst',
  'Nokia Product Designer',
  'Noodle.ai Senior Data Scientist',
  'Oracle Applications Engineer',
  'Oracle Senior Software Engineer',
  'Oracle Principal Software Engineer',
  'Oracle Senior Applications Engineer',
  'Oracle Product Manager',
  'Oracle Data Analyst',
  'Oracle UX Designer',
  'Oracle Interaction Designer',
  'Outreach Product Expert',
  'Outreach Product UI Designer',
  'Palantir QA Engineer',
  'Palantir Product Quality Engineer',
  'Palantir Product Manager',
  'Palantir Senior Product Manager',
  'Palantir Product Expert',
  'Palantir Data Scientist',
  'Palantir Data Analyst',
  'Palo Alto Networks Software Engineer',
  'Palo Alto Networks Technical Support Engineer',
  'Panasonic Software Engineer',
  'Panasonic Product Manager',
  'Panasonic Data Analyst',
  'Pandora Software Engineer',
  'Pandora Product Manager',
  'Pandora Data Analyst',
  'Pandora Graphic Designer',
  'PayPal Senior Software Engineer',
  'PayPal Product Manager',
  'PayPal Senior Product Manager',
  'PayPal Program Manager',
  'PayPal Senior UX Designer',
  'PayPal UI Designer',
  'Qualcomm Hardware Engineer',
  'Qualcomm Senior Software Engineer',
  'Qualcomm Systems Engineer',
  'Qualcomm Associate Engineer',
  'Qualcomm Staff Engineer',
  'Qualcomm Digital Design Engineer',
  'Qualcomm Product Manager',
  'Qualcomm Data Scientist',
  'Qualcomm Research Scientist',
  'Qualcomm UI Developer',
  'Quora Product Manager',
  'Quora Data Scientist',
  'Quora UX Researcher',
  'Red Hat Senior Software Engineer',
  'Red Hat Product Manager',
  'Red Hat Principal Product Manager',
  'Red Hat Data Scientist',
  'Red Hat UI Designer',
  'Reddit Software Engineer',
  'Reddit Senior Software Engineer',
  'Reddit Product Manager',
  'Reddit Data Scientist',
  'Reddit Interaction Designer',
  'Ripple Product Manager',
  'Robinhood User Researcher',
  'Robinhood Senior UI Developer',
  'Salesforce Solutions Engineer',
  'Salesforce Lead Solutions Engineer',
  'Salesforce Senior Solutions Engineer',
  'Salesforce Product Manager',
  'Salesforce Data Scientist',
  'Salesforce Senior Data Scientist',
  'Salesforce Product Designer',
  'Salesforce Senior Product Designer',
  'Salesforce Senior UX Designer',
  'Salesforce Interaction Designer',
  'Samsara Senior Software Engineer',
  'Samsara Customer Support Engineer',
  'Samsara Product Designer',
  'Samsara Senior Product Designer',
  'Samsung Senior Software Engineer',
  'Samsung Lead Engineer',
  'Samsung Hardware Engineer',
  'Samsung Product Manager',
  'Samsung Junior Data Scientist',
  'Samsung Data Analyst',
  'Samsung Machine Learning Scientist',
  'Samsung UX Designer',
  'Samsung Visual Designer',
  'Samsung Industrial Designer',
  'SAP Senior Software Engineer',
  'SAP Product Owner',
  'SAP UX Designer',
  'SAP Senior UX Designer',
  'Seagate Technology Firmware Engineer',
  'Seagate Technology Software Engineer',
  'Seagate Technology Staff Engineer',
  'Seagate Technology Senior Engineer',
  'Seagate Technology Engineering Specialist',
  'Seagate Technology Process Engineer',
  'Seagate Technology Research Scientist',
  'Seagate Technology Data Analyst',
  'Seagate Technology Senior Visual Designer',
  'Snap Inc. Software Engineer',
  'Snap Inc. Product Manager',
  'Snap Inc. Program Manager',
  'Snap Inc. Product Designer',
  'Snap Inc. UI Designer',
  'Sony Software Engineer',
  'Sony Senior Software Engineer',
  'Sony Trainee Software Engineer',
  'Sony Design Engineer',
  'Sony Product Manager',
  'Sony Data Analyst',
  'Sony Product Designer',
  'Soundcloud Product Manager',
  'Soundcloud Data Analyst',
  'Soundcloud Product Designer',
  'Splunk Senior Software Engineer',
  'Spotify Senior Software Engineer',
  'Spotify Software Engineer (Back-end)',
  'Spotify Machine Learning Engineer',
  'Spotify Android Engineer',
  'Spotify Research Scientist',
  'Spotify Research Lead',
  'Spotify Interaction Designer',
  'STMicroelectronics Software Engineer',
  'STMicroelectronics Design Engineer',
  'STMicroelectronics Senior Design Engineer',
  'STMicroelectronics Process Engineer',
  'STMicroelectronics Analog Designer',
  'Stripe Senior Software Engineer',
  'Stripe Product Support, Market Manager'
];

(async () => {
  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    const csvWriter = createCsvWriter({
      path: `urls.csv`,
      header: [{ id: 'urls', title: 'urls' }, { id: 'pages', title: 'pages' }],
      fieldDelimiter: ';'
    });
    for (let i = 0; i < positions.length; i++) {
      await page.goto('https://google.com');
      await page.waitForSelector('.gLFyf');
      await page.waitForSelector('.RNmpXc');
      await page.type(
        '.gLFyf',
        `${positions[i]} interview questions glassdoor`,
        { delay: 100 }
      );
      await page.evaluate(() => {
        document.querySelector('input[name=btnI]').click();
      });
      await page.waitForSelector('h1.h2');
      console.log(page.url());
      let url = await page.url();
      console.log(url);
      url = url.replace(/\.htm$/, '_IP2000.htm');
      console.log(url);
      await page.goto(url);
      await page.waitForSelector('span.disabled');
      const pageno = await page.evaluate(() => {
        return document.querySelector('span.disabled').innerText;
      });

      console.log(pageno);
      data.push({ urls: url, pages: pageno });
    }
    csvWriter
      .writeRecords(data)
      .then(() => console.log('The CSV file was written successfully'));
    await browser.close();
  } catch (err) {
    console.log(err);
  }
})();
